	const arraySemana = [
        {		
            "fecha":"2021/09/20",
            "hora":1,
            "modulo":2,
            "uf":4,
            "profesor":"J.E",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/20",
            "hora":2,
            "modulo":7,
            "uf":1,
            "profesor":"J.E",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/20",
            "hora":3,
            "modulo":7,
            "uf":1,
            "profesor":"J.E",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/20",
            "hora":4,
            "modulo":3,
            "uf":1,
            "profesor":"C.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/20",
            "hora":5,
            "modulo":3,
            "uf":1,
            "profesor":"C.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/21",
            "hora":1,
            "modulo":6,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/21",
            "hora":2,
            "modulo":6,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/21",
            "hora":3,
            "modulo":6,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/21",
            "hora":4,
            "modulo":9,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/21",
            "hora":5,
            "modulo":9,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
       
        
    
        {		
            "fecha":"2021/09/22",
            "hora":1,
            "modulo":7,
            "uf":1,
            "profesor":"J.E",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/22",
            "hora":2,
            "modulo":7,
            "uf":1,
            "profesor":"J.E",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/22",
            "hora":3,
            "modulo":5,
            "uf":1,
            "profesor":"A.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/22",
            "hora":4,
            "modulo":5,
            "uf":1,
            "profesor":"A.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/22",
            "hora":5,
            "modulo":3,
            "uf":1,
            "profesor":"C.R",
            "aula":"T6"
        },
        
        
        {		
            "fecha":"2021/09/23",
            "hora":1,
            "modulo":8,
            "uf":4,
            "profesor":"A.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/23",
            "hora":2,
            "modulo":8,
            "uf":4,
            "profesor":"A.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/23",
            "hora":3,
            "modulo":8,
            "uf":4,
            "profesor":"A.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/23",
            "hora":4,
            "modulo":9,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/23",
            "hora":5,
            "modulo":9,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
    
    
        {		
            "fecha":"2021/09/24",
            "hora":1,
            "modulo":6,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/24",
            "hora":2,
            "modulo":6,
            "uf":1,
            "profesor":"C.A",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/24",
            "hora":3,
            "modulo":3,
            "uf":1,
            "profesor":"C.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/24",
            "hora":4,
            "modulo":3,
            "uf":1,
            "profesor":"C.R",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/24",
            "hora":5,
            "modulo":7,
            "uf":1,
            "profesor":"J.E",
            "aula":"T6"
        },
        {		
            "fecha":"2021/09/24",
            "hora":6,
            "modulo":7,
            "uf":1,
            "profesor":"J.E",
            "aula":"T7"
        }
    ]
    	
	

